version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: ./outputs/hfsl_backend_scraper.log
  # email:
  #   class: logging.handlers.SMTPHandler
  #   level: WARNING
  #   mailhost: smtp.gmail.com
  #   fromaddr: to@address.co.uk
  #   toaddrs: to@address.co.uk
  #   subject: Oh no, something's gone wrong!
  #   credentials: [email, password]
  #   secure: []
root:
  level: INFO
  handlers: [console, file]
  propagate: True